# -*- coding: utf-8 -*-
"""音声を生成せずに、原稿から「推定タイミングの字幕データ」を作る。

インターネット(edge-tts)が使えない環境向けのフォールバック。
実測ではなく推定値なので、音声を作れる環境では tools/gen_audio.py を使うこと。

使い方:  python tools/estimate_captions.py   (リポジトリルートで実行)
"""
import json
import re
from pathlib import Path

from script_segments import SEGMENTS, VOICE

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "assets" / "audio"

CPS = 5.8      # ja-JP-KeitaNeural の実測平均(文字/秒)
GAP = 0.25     # 文と文の間
TAIL = 0.7     # 最終文のあとの余韻


def split_sentences(text):
    parts = [p for p in re.split(r"(?<=。)", text) if p.strip()]
    return parts or [text]


def build(text):
    cues, t = [], 0.1
    for s in split_sentences(text):
        e = t + len(s) / CPS
        cues.append({"t": round(t, 3), "e": round(e, 3), "text": s})
        t = e + GAP
    return {"dur": round(cues[-1]["e"] + TAIL, 3), "cues": cues}


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    results = [build(t) for t in SEGMENTS]
    payload = json.dumps(results, ensure_ascii=False)
    js = (
        "// generated by tools/estimate_captions.py — 推定タイミング(音声なし)\n"
        "// 音声つきで書き出す場合は tools/gen_audio.py を実行して上書きすること。\n"
        "window.NARRATION_AUDIO = false;\n"
        "window.NARRATION = %s;\n" % payload
    )
    (OUT / "captions.js").write_text(js, encoding="utf-8")
    for i, r in enumerate(results, 1):
        print(f"scene-{i:02d}: {r['dur']:6.1f}s  {len(r['cues'])} cues")
    print(f"total: {sum(r['dur'] for r in results):.1f}s  ({VOICE} 想定) -> {OUT / 'captions.js'}")


if __name__ == "__main__":
    main()
