# -*- coding: utf-8 -*-
"""原稿セグメントから edge-tts (ja-JP-KeitaNeural) でナレーションMP3と
文単位の同期字幕データ (assets/audio/captions.js) を生成する。

原稿は tools/script_segments.py にあるので、文言修正はそちらを編集する。

使い方:  pip install edge-tts
        python tools/gen_audio.py   (リポジトリルートで実行・要インターネット)
"""
import asyncio
import json
from pathlib import Path

import edge_tts

from script_segments import SEGMENTS, VOICE

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "assets" / "audio"


async def gen_segment(index, text):
    mp3_path = OUT / f"scene-{index:02d}.mp3"
    communicate = edge_tts.Communicate(text, VOICE)
    cues = []
    with open(mp3_path, "wb") as f:
        async for chunk in communicate.stream():
            if chunk["type"] == "audio":
                f.write(chunk["data"])
            elif chunk["type"] in ("SentenceBoundary", "WordBoundary"):
                start = chunk["offset"] / 1e7
                end = (chunk["offset"] + chunk["duration"]) / 1e7
                cues.append({"t": round(start, 3), "e": round(end, 3), "text": chunk["text"]})
    duration = round((cues[-1]["e"] if cues else 0) + 0.7, 3)
    print(f"scene-{index:02d}: {duration:6.1f}s  {len(cues)} cues  {mp3_path.stat().st_size//1024} KB")
    return {"dur": duration, "cues": cues}


async def main():
    OUT.mkdir(parents=True, exist_ok=True)
    results = []
    for i, text in enumerate(SEGMENTS, 1):
        results.append(await gen_segment(i, text))
    payload = json.dumps(results, ensure_ascii=False)
    js = (
        "// generated by tools/gen_audio.py — voice: %s\n"
        "window.NARRATION_AUDIO = true;\n"
        "window.NARRATION = %s;\n" % (VOICE, payload)
    )
    (OUT / "captions.js").write_text(js, encoding="utf-8")
    total = sum(r["dur"] for r in results)
    print(f"total: {total:.1f}s  -> {OUT / 'captions.js'}")


if __name__ == "__main__":
    asyncio.run(main())
