# -*- coding: utf-8 -*-
"""原稿セグメントから edge-tts (ja-JP-KeitaNeural) でナレーションMP3と
文単位の同期字幕データ (assets/audio/captions.js) を生成する。

原稿は tools/script_segments.py にあるので、文言修正はそちらを編集する。

生成中に接続が切れると「途中までのMP3」ができてしまうため、
1シーンごとに読み上げが最後まで届いたかを検査し、欠けていれば自動で作り直す。
12シーンすべてが揃ったときだけ captions.js を書き出す(音声と字幕のズレを防ぐ)。

使い方:  pip install edge-tts
        python tools/gen_audio.py         (全シーン生成・リポジトリルートで実行・要インターネット)
        python tools/gen_audio.py 11      (指定シーンだけ作り直し。他は既存の captions.js を引き継ぐ)
"""
import asyncio
import json
import re
import sys
from pathlib import Path

import edge_tts

from script_segments import SEGMENTS, VOICE, READINGS, tts_text

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "assets" / "audio"

ATTEMPTS = 4          # 1シーンあたりの試行回数
COVERAGE_MIN = 0.97   # 読み上げが原稿の何割に達していれば完走とみなすか
MAX_CPS = 8.5         # ja-JP-KeitaNeural の実測は 5〜6 文字/秒。これを超えたら尺が足りない


class Incomplete(Exception):
    """途中で切れた(最後まで読み上げられなかった)ことを表す。"""


async def synthesize(index, text):
    """1シーンを生成して (bytes, cues) を返す。完走していなければ Incomplete。"""
    speak = tts_text(text)  # 読みだけ差し替えたテキストで発話する
    communicate = edge_tts.Communicate(speak, VOICE)
    audio = bytearray()
    cues = []
    async for chunk in communicate.stream():
        if chunk["type"] == "audio":
            audio.extend(chunk["data"])
        elif chunk["type"] in ("SentenceBoundary", "WordBoundary"):
            start = chunk["offset"] / 1e7
            end = (chunk["offset"] + chunk["duration"]) / 1e7
            cues.append({"t": round(start, 3), "e": round(end, 3), "text": chunk["text"]})

    if not audio or not cues:
        raise Incomplete("音声が返ってきませんでした")

    # 1) 字幕として返ってきた文字数が、原稿にどれだけ届いているか
    spoken = sum(len(c["text"]) for c in cues)
    coverage = spoken / max(1, len(speak))
    # 2) 尺そのものが足りていないか(切れたMP3は極端に短くなる)
    duration = cues[-1]["e"] + 0.7
    cps = len(speak) / max(0.1, duration)
    if coverage < COVERAGE_MIN or cps > MAX_CPS:
        raise Incomplete(
            f"読み上げが途中で切れています(原稿の{coverage:.0%}・{cps:.1f}文字/秒)"
        )
    # 字幕の表示は元の表記に戻す(読み差し替えの逆変換)
    for cue in cues:
        for surface, reading in READINGS.items():
            cue["text"] = cue["text"].replace(reading, surface)
    return bytes(audio), cues, round(duration, 3)


async def gen_segment(index, text):
    for attempt in range(1, ATTEMPTS + 1):
        try:
            audio, cues, duration = await synthesize(index, text)
        except Exception as e:  # 接続断・途中切れの両方をここで拾う
            reason = e if isinstance(e, Incomplete) else f"{type(e).__name__}: {e}"
            if attempt == ATTEMPTS:
                print(f"scene-{index:02d}: 失敗（{ATTEMPTS}回試行）— {reason}")
                return None
            wait = 2 ** attempt
            print(f"scene-{index:02d}: やり直します（{attempt}回目 — {reason}）… {wait}秒待機")
            await asyncio.sleep(wait)
            continue

        # 検査を通ったものだけをファイルに書く(壊れたMP3で上書きしない)
        mp3_path = OUT / f"scene-{index:02d}.mp3"
        mp3_path.write_bytes(audio)
        print(f"scene-{index:02d}: {duration:6.1f}s  {len(cues)}文  {len(audio) // 1024} KB")
        return {"dur": duration, "cues": cues}


def load_existing():
    """既存の captions.js から NARRATION 配列を読み出す(部分再生成用)。"""
    path = OUT / "captions.js"
    if not path.exists():
        return None
    m = re.search(r"window\.NARRATION = (\[.*\]);", path.read_text(encoding="utf-8"), re.S)
    if not m:
        return None
    data = json.loads(m.group(1))
    return data if len(data) == len(SEGMENTS) else None


async def main():
    OUT.mkdir(parents=True, exist_ok=True)

    targets = None  # None = 全シーン
    if len(sys.argv) > 1:
        targets = {int(a) for a in sys.argv[1:]}
        bad = [i for i in targets if not 1 <= i <= len(SEGMENTS)]
        if bad:
            print(f"シーン番号は 1〜{len(SEGMENTS)} で指定してください: {bad}")
            return 1
        existing = load_existing()
        if existing is None:
            print("既存の captions.js が読めないため、部分再生成はできません。")
            print("引数なしで実行して全シーンを生成してください。")
            return 1

    results = []
    for i, text in enumerate(SEGMENTS, 1):
        if targets is not None and i not in targets:
            results.append(existing[i - 1])
            continue
        results.append(await gen_segment(i, text))

    failed = [i for i, r in enumerate(results, 1) if r is None]
    if failed:
        print()
        print("生成できなかったシーン: " + ", ".join(f"scene-{i:02d}" for i in failed))
        print("captions.js は更新していません（音声と字幕がズレるため）。")
        print("ネットワークの状態を確認して、もう一度実行してください。")
        return 1

    payload = json.dumps(results, ensure_ascii=False)
    js = (
        "// generated by tools/gen_audio.py — voice: %s\n"
        "window.NARRATION_AUDIO = true;\n"
        "window.NARRATION = %s;\n" % (VOICE, payload)
    )
    (OUT / "captions.js").write_text(js, encoding="utf-8")
    total = sum(r["dur"] for r in results)
    print(f"total: {total:.1f}s  ({len(results)}シーン)  -> {OUT / 'captions.js'}")
    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
